### ISSUE TITLE
Accepting PRs?

### ISSUE THREAD

**Issue by petemounce** [azavea/ansible-buildkite-agent#1]
Hi there - I'm doing some work with buildkite and came across this. Thanks for sharing!

I just wondered whether you're likely to accept PRs? The new v3 agent is out, so there are some differences, probably. I also run inside GCE, so there's another variable to deal with. Things like that?

**Comment by petemounce** [comment]
#2 and #3 await your attention. I've combined them into my own branch `improbable` and successfully installed the agent, passing my https://goss.rocks tests (which I had, before, when I was installing the agent via script). So, I'm reasonably confident, but happy to make changes if necessary.

**Comment by hectcastro** [comment]
Yes, please.

Thanks for taking the time to make these PRs, @petemounce. I went through and attempted reviews for each.
