### ISSUE TITLE
Windows & macOS support welcome?

### ISSUE THREAD

**Issue by petemounce** [azavea/ansible-buildkite-agent#5]
Hi there - would you welcome PR(s) that add Windows & macOS support? It would be really convenient to me if this were the only role I needed to deal with to match my needs around cross-platform buildkite-CI.

**Comment by hectcastro** [comment]
Thanks for checking-in, @petemounce. We would definitely welcome PRs to add support for those operating systems, as long as they don't compromise the Linux support.

**Comment by petemounce** [comment]
Thanks @tommeier for macOS! #7.
